spring:
  profiles:
    active: local

#local 환경
---
spring:
  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test

#운영 환경
---
#spring:
#  profiles: set1
#  spring.porifles.include: real-db